#! /bin/bash
#
# Don't use this with 10_ssh.sh if you have.
#
# 10_ssh.sh generates a key and copies the pubkey associated with the key
# to the cds and lb.
#
# This script doesn't generate a key. It just copies the pubkey associated
# with the key generated by rhui-manager.
#
# Use with:
# - 71_setup_cds_rhua.sh
# - 76_setup_haproxy_rhua.sh
#
# Don't use with:
# - 10_ssh.sh
# - 70_setup_cds.sh
# - 75_setup_haproxy.sh
#
set -ex

source ${0%/*}/config.sh

for cds in ${CDS_SERVERS:?} ${LB_SERVERS:?}; do
    ssh-copy-id -i /root/.ssh/id_rsa_rhua ${cds}
done

# Check
for cds in ${CDS_SERVERS:?} ${LB_SERVERS:?}; do
    echo "# Check ${cds}"
    ssh -i /root/.ssh/id_rsa_rhua $cds "test -f ./setup/check.sh && time ./setup/check.sh || (hostname -f; date; ip a; ip r)"
done

# vim:sw=4:ts=4:et:
